//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyassignmentEntities : DbContext
    {
        public MyassignmentEntities()
            : base("name=MyassignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MapTable> MapTables { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    
        public virtual ObjectResult<getAll_Result> getAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAll_Result>("getAll");
        }
    
        public virtual ObjectResult<Customer> fun_getAllCustomerss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("fun_getAllCustomerss");
        }
    
        public virtual ObjectResult<Customer> fun_getAllCustomerss(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("fun_getAllCustomerss", mergeOption);
        }
    
        public virtual ObjectResult<getAllLocations_Result> getAllLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllLocations_Result>("getAllLocations");
        }
    
        public virtual ObjectResult<Location> fun_getLocations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Location>("fun_getLocations");
        }
    
        public virtual ObjectResult<Location> fun_getLocations(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Location>("fun_getLocations", mergeOption);
        }
    }
}
